name: Test

on: [ push, pull_request ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.1.0
      - uses: jitterbit/get-changed-files@v1
        id: abc
        with:
          format: space-delimited
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Run Spider
        run: |
          directory = "spiders"
          for changed_file in ${{ steps.abc.outputs.added_modified }}; do
            test "${string#*$directory}" != "$string" && echo "$directory found in $changed_file"

            if [ changed_file == *"spiders"* ]; then
              echo "Do something with this ${changed_file}."
            fi
          done
          echo "Testing"
